services:
  backend:
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run devStart
    environment:
      - NODE_ENV=development
    restart: unless-stopped


  frontend:
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run dev -- --host 0.0.0.0 --port 4173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped

  db:
    # Tietokanta ei tarvitse overrideja kehitysvaiheessa
    restart: unless-stopped
